databases:
  - name: search_analytics_db
    databaseName: search_analytics_prod
    user: search_analytics_user

services:
  - type: web
    name: search_analytics_web
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: PORT
        value: 10000
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
      - key: RACK_ENV
        value: production
      - key: RAILS_ENV
        value: production
        fromDatabase:
          name: search_analytics_db
          property: connectionString