default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>
development:
  <<: *default
  database: search_analytics

test:
  <<: *default
  database: search_analytics

production:
  <<: *default
  database: search_analytics_production